---
title: "1953188"
author: "Arya Nanda Mahardika Putra"
tittle: "Support Vector Machine"
Date: 11
output: html_notebook
---

```{r}
#importing the datarya	
library(mlbench)
datarya <- Glass 
datarya <- datarya[8:10]
datarya
```

```{r}
# Encoding the target feature as a factor
datarya$Type = factor(datarya$Type, levels = c(1:10))
datarya
```


```{r}
#splitting the dataset
library(caTools)

set.seed(123)
split = sample.split(datarya$Type, SplitRatio = 0.75)

training_set = subset(datarya, split == TRUE)
test_set = subset(datarya, split == FALSE)
training_set
test_set

```

```{r}
training_set[-3] = scale(training_set[-3])
test_set[-3] = scale(test_set[-3])
training_set

```

```{r}
# Fitting SVM to the Training set 
library(e1071) 

classifier = svm(formula = Type ~ ., 
				data = training_set, 
				type = 'C-classification',
				kernel = 'linear')
classifier

```
```{r}
# Predicting the Test set results 
y_pred = predict(classifier, newdata = test_set[-3]) 
y_pred

```
```{r}
# Making the Confusion Matrix 
cm = table(test_set[, 3], y_pred) 
cm
```
```{r}
# Plotting the training data set results 
set = training_set 
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01) 
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01) 

grid_set = expand.grid(X1, X2) 
colnames(grid_set) = c('Ba', 'Fe') 
y_grid = predict(classifier, newdata = grid_set) 

plot(set[, -3], 
	main = 'SVM (Training set)', 
	xlab = 'Ba', ylab = 'Fe', 
	xlim = range(X1), ylim = range(X2)) 

contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE) 

points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'coral1', 'aquamarine')) 

points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', 'red3')) 

```
```{r}
set = test_set 
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01) 
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01) 

grid_set = expand.grid(X1, X2) 
colnames(grid_set) = c('Ba', 'Fe') 
y_grid = predict(classifier, newdata = grid_set) 

plot(set[, -3], main = 'SVM (Test set)', 
	xlab = 'Ba', ylab = 'Fe', 
	xlim = range(X1), ylim = range(X2)) 

contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE) 

points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'coral1', 'aquamarine')) 

points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', 'red3')) 

```



